import { StyleSheet, Dimensions } from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

export default StyleSheet.create({
  button: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    width: 340,
    height: 60,
    borderColor: '#3E721E',
    borderRadius: 8,
    marginTop: 70,
    borderWidth: 1.5,
    marginVertical: -45,
  },
  buttonA: {
    backgroundColor: '#8BC63F',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    width: windowWidth * 0.65,
    height: windowWidth * 0.1,
    borderColor: '#3E721E',
    borderRadius: 8,
    borderWidth: 1.5,
  },
  buttonB: {
    backgroundColor: '#1F6A39',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    width: windowWidth * 0.65,
    height: windowWidth * 0.1,
    borderColor: '#3E721E',
    borderRadius: 8,
    borderWidth: 1.5,
  },
  eventButton: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    width: 350,
    height: 100,
    borderColor: '#3E721E',
    borderRadius: 8,
    marginVertical: 35,
    borderWidth: 1.5,
  },
  iconEvent: {
    width: 80,
    height: 80,
    borderRadius: 8,
  },
  eventButtonText: {
    color: '#372A0B',
    fontWeight: 'bold',
    fontSize: 18,
    marginTop: -90,
    marginLeft: 150,
  },
  eventButtonDate: {
    color: '#8BC63F',
    fontWeight: 'bold',
    fontSize: 15,
    marginLeft: 150,
  },
  singleEventPic: {
    justifyContent: 'center',
    width: 350,
    height: 200,
    borderColor: '#3E721E',
    borderRadius: 8,
    marginVertical: 15,
    borderWidth: 1.5,
    marginBottom: -40,
  },
  singleEventIcon: {
    width: 35,
    height: 35,
    tintColor: '#8BC63F',
    resizeMode: 'contain',
  },
  eventContainer: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    width: 340,
    height: 60,
  },
  containerButton: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    width: 340,
    height: 60,
    marginTop: 75,
  },
  buttonText: {
    color: '#372A0B',
    fontWeight: 'bold',
    marginHorizontal: 60,
    fontSize: 18,
  },
  seeAll: {
    fontSize: 18,
    textAlign: 'right',
    marginHorizontal: 30,
    color: '#CE9F20',
    marginBottom: 150,
  },

  kindabrown: {
    color: '#CE9F20',
    fontSize: 18,
  },
  seeAllEvent: {
    fontSize: 18,
    textAlign: 'right',
    marginHorizontal: 30,
    color: '#CE9F20',
    marginVertical: windowHeight * 0.18,
    //marginBottom: 220,
  },
  iconsGuide: {
    width: 30,
    height: 30,
    tintColor: '#8BC63F',
    marginBottom: -28,
    marginHorizontal: 15,
    marginVertical: -28,
    resizeMode: 'contain',
  },
  iconGuide: {
    width: 30,
    height: 30,
    marginBottom: -28,
    alignSelf: 'flex-end',
    marginHorizontal: 10,
    marginVertical: -28,
  },
  iconsGuide1: {
    tintColor: '#CE9F20',
    width: 40,
    height: 40,
    marginBottom: -33,
    marginHorizontal: 10,
    marginVertical: -30,
    resizeMode: 'contain',
  },
  logout: {
    fontSize: 18,
    marginHorizontal: 60,
    fontWeight: 'bold',
    color: '#CE9F20',
  },
  separator: {
    height: 1,
    backgroundColor: '#CED0CE',
  },
});
