import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  button: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    width: 340,
    height: 60,
    borderColor: '#3E721E',
    borderRadius: 8,
    marginTop: 70,
    borderWidth: 1.5,
    marginVertical: -45,
  },
  eventButton: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    width: 400,
    height: 100,
    borderColor: '#3E721E',
    borderRadius: 8,
    marginVertical: 35,
    borderWidth: 1.5,
  },
  iconEvent: {
    width: 80,
    height: 80,
    alignSelf: 'flex-start',
    marginHorizontal: 10,
    marginBottom: 90,
    borderRadius: 8,
  },
  eventButtonText: {
    color: '#372A0B',
    fontWeight: 'bold',
    marginLeft: 95,
    fontSize: 18,
  },
  eventButtonDate: {
    color: '#8BC63F',
    fontWeight: 'bold',
    marginLeft: 95,
    fontSize: 15,
    marginTop: -140,
  },
  singleEventPic: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    width: 350,
    height: 200,
    borderColor: '#3E721E',
    borderRadius: 8,
    marginVertical: 15,
    borderWidth: 1.5,
    marginBottom: -40,
  },
  singleEventIcon: {
    width: 35,
    height: 35,
    tintColor: '#8BC63F',
    resizeMode: 'contain',
  },
  eventContainer: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    width: 340,
    height: 60,
  },
  containerButton: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    width: 340,
    height: 60,
    marginTop: 75,
  },
  buttonText: {
    color: '#372A0B',
    fontWeight: 'bold',
    marginHorizontal: 60,
    fontSize: 18,
  },
  seeAll: {
    fontSize: 18,
    textAlign: 'right',
    marginHorizontal: 30,
    color: '#CE9F20',
    marginBottom: 150,
  },
  seeAllEvent: {
    fontSize: 18,
    textAlign: 'right',
    marginHorizontal: 30,
    color: '#CE9F20',
    marginBottom: 220,
  },
  iconsGuide: {
    width: 30,
    height: 30,
    tintColor: '#8BC63F',
    marginBottom: -28,
    marginHorizontal: 15,
    marginVertical: -28,
    resizeMode: 'contain',
  },
  iconGuide: {
    width: 30,
    height: 30,
    marginBottom: -28,
    alignSelf: 'flex-end',
    marginHorizontal: 10,
    marginVertical: -28,
  },
  iconsGuide1: {
    tintColor: '#CE9F20',
    width: 40,
    height: 40,
    marginBottom: -33,
    marginHorizontal: 10,
    marginVertical: -30,
    resizeMode: 'contain',
  },
  logout: {
    fontSize: 18,
    marginHorizontal: 60,
    fontWeight: 'bold',
    color: '#CE9F20',
  },
});
